### ISSUE TITLE
all excitation chambers and private coops disappeared

### ISSUE THREAD

**Issue by Boomer-1** [kii-chan-reloaded/GeneticChickengineering#15]
I got my console full of error logs and everyone of my excitation chambers and coops disappeared.

here's the errors in pastebin

https://pastebin.com/MXsBgdid

mc 1.16.5
Dev 925 for SF

**Comment by DizaEx** [comment]
yeaa i have same issue

**Comment by Kbryst** [comment]
same same, heres the extra stuff from the slimefun error log

`Stacktrace:

java.lang.NoSuchMethodError: 'boolean space.kiichan.geneticchickengineering.machines.ExcitationChamber.isProcessing(org.bukkit.block.Block)'
	at space.kiichan.geneticchickengineering.machines.ExcitationChamber.tick(ExcitationChamber.java:100)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:339)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:188)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:175)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:145)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:114)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)`

**Comment by Waffel5844** [comment]
I have the same problem

**Comment by bobhenl** [comment]
```
java.lang.NoSuchMethodError: space.kiichan.geneticchickengineering.machines.ExcitationChamber.isProcessing(Lorg/bukkit/block/Block;)Z
	at space.kiichan.geneticchickengineering.machines.ExcitationChamber.tick(ExcitationChamber.java:100)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:339)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:188)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:175)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:145)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:114)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:58)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by mrcoffee1026** [comment]
confirmed:
private coop: https://pastebin.com/yuq72wkK
excitation chamber: https://pastebin.com/556S6k1Q

Paper git-Paper-759 (MC: 1.16.5)
Slimefun DEV - 930 (git 0224f94e)
Metrics-Module #22
Java 11

Installed Addons: (34)
  GlobalWarming vDEV - 9 (git d21d264b)
  ExtraTools vDEV - 26 (git 0cb2ad70)
  FoxyMachines vDEV - 45 (git ce4f8193)
  SlimefunOreChunks vDEV - 13 (git 9f7a2be3)
  SensibleToolbox vDEV - 40 (git f3e782d3)
  SimpleMaterialGenerators vDEV - 6 (git 2083e132)
  DynaTech vDEV - 122 (git ed16c149)
  ExtraGear vDEV - 12 (git 4570ea2c)
  MoreTools vDEV - 10 (git 660e2ce6)
  InfinityExpansion vDEV - 114 (git 9d5d3cec)
  SFCalc vDEV - 24 (git 2574e3e0)
  ElectricSpawners vDEV - 22 (git 4cb2c56b)
  ExtraHeads vDEV - 21 (git a2c68d59)
  MobCapturer vDEV - 15 (git a42c9e0c)
  SlimyTreeTaps vDEV - 19 (git 69930ef7)
  PrivateStorage vDEV - 17 (git 43d35d74)
  TranscEndence vDEV - 34 (git eece87db)
  GeneticChickengineering vDEV - 13 (git 37cffcbb)
  FluffyMachines vDEV - 84 (git cf78f53a)
  CMI v8.8.4.8
  ChestTerminal vDEV - 43 (git 3096bab5)
  DyedBackpacks vDEV - 15 (git 5f5e8b9e)
  SoundMuffler vDEV - 21 (git 3206933b)
  SlimefunWarfare vDEV - 38 (git fceefb72)
  EcoPower vDEV - 4 (git 2a08d31d)
  HotbarPets vDEV - 37 (git 63b1553e)
  SlimefunLuckyBlocks vDEV - 35 (git 3b6586d6)
  ExoticGarden vDEV - 76 (git d148a362)
  Liquid vDEV - 11 (git bea52454)
  SlimeCustomizer vDEV - 7 (git 380c5f03)
  LiteXpansion vDEV - 151 (git e9e64576)
  SimpleUtils vDEV - 8 (git 1505dfa3)
  SoulJars vDEV - 22 (git aded79dd)
  SlimyRepair vDEV - 3 (git c56293bb)

**Comment by Seggan** [comment]
i think i can do a pr for this

**Comment by silvermirrow** [comment]
So I think one of the problems,  the obvious one, is about the missing function about "bool isProcessing( )".

**Comment by Seggan** [comment]
thats not how java works. you are thinking in c++ terms

**Comment by silvermirrow** [comment]
Okay, u know how java works. So.... where does this "isProcessing" come from? Can we skip it, or the functions used in chamber and coop within it?

**Comment by Boomer-1** [comment]
doesn't matter. Only Kii-chan can fix this. Unless she logs into her account and codes the fix, it is a moot point. It's a quick fix from an update in SF that a few addons were not coded for. and you can't use the addon without the chamber and coop so the only thing we can do right now is hope she logs in and fixes it. If not, then may it rest in peace.

**Comment by Boomer-1** [comment]
@kii-chan-reloaded any chance on getting this fixed?

**Comment by ybw0014** [comment]
https://github.com/kii-chan-reloaded/GeneticChickengineering/issues/21
boomer, its time to close this
