### ISSUE TITLE
all excitement chambers disappear

### ISSUE THREAD

**Issue by JavierWxw** [kii-chan-reloaded/GeneticChickengineering#16]
2021-06-02-02-14.err's contents:

Error Generated: 2021-06-02-02-14

Java Environment:
  Operating System: Linux
  Java Version: 16.0.1

Server Software: Paper
  Build: git-Paper-757 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 930 (git 0224f94e)
  Caused by: GeneticChickengineering vDEV - 13 (git 37cffcbb)

Installed Addons (15)
  + SlimefunOreChunks DEV - 13 (git 9f7a2be3)
  + ExtraHeads DEV - 21 (git a2c68d59)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + FluffyMachines DEV - 84 (git cf78f53a)
  + DyedBackpacks DEV - 15 (git 5f5e8b9e)
  + SensibleToolbox DEV - 40 (git f3e782d3)
  + ExtraGear DEV - 12 (git 4570ea2c)
  + SFCalc DEV - 24 (git 2574e3e0)
  + TranscEndence DEV - 34 (git eece87db)
  + GeneticChickengineering DEV - 13 (git 37cffcbb)
  + ChestTerminal DEV - 43 (git 3096bab5)
  + HeadLimiter DEV - 3 (git 58cfca94)
  + LiteXpansion DEV - 152 (git daa388b9)
  + InfinityExpansion DEV - 114 (git 9d5d3cec)
  - DynaTech DEV - 121 (git ef38d195)

Installed Plugins (85):
  + HackedCore 2.71.4
  + FarmControl 1.1.5
  + AntiCreeper 5.1
  + PlaceholderAPI 2.10.9
  + ezBroadcast 1.2
  + SkinsRestorer 14.0.2
  + TabCompleteFilter 1.0.8
  + LightAPI 3.4.6
  + HPWP 1.2.3
  + LuckPerms 5.3.3
  + LoginSecurity 3.0.2
  + VillagerOptimiser 1.1.5
  + HackedServer 2.78.2
  + Votifier 2.7.2
  + ProtocolLib 4.6.0
  + LibsDisguises 10.0.24
  + InventoryRollback 1.4.0
  + UberEnchant 8.9.3
  + KrakenMobcoins 2.2
  + Vault 1.7.3-b131
  + FastLogin 1.11-SNAPSHOT-7192dcd
  + PerWorldInventory 2.3.2
  + Instruments 1.7
  + CustomHeads 3.0.2
  + XP-Deposit 4.3.1
  + PlayerKits 2.15.1
  + Essentials 2.18.2.0
  + AdvancedBan 2.3.0
  + VotingPlugin 6.3.2
  + FastAsyncWorldEdit 1.16-697;b599769
  + Bitcoin 2.5
  + TradeSystem 2.0.1
  + EssentialsChat 2.18.2.0
  + TAB 2.8.10
  + WorldGuard 7.0.4+f7ff984
  + antiRedstoneClock 1.4.1
  + EssentialsProtect 2.18.2.0
  + EssentialsAntiBuild 2.18.2.0
  + EssentialsSpawn 2.18.2.0
  + WorldGuardExtraFlags 4.1.5-SNAPSHOT
  + Harbor 1.6.3
  + Essentials_WarpGUI 2.2.2
  + GadgetsMenu 4.6.5
  + Jobs 4.17.2
  + Citizens 2.0.27-SNAPSHOT (build 2316)
  + WolfyUtilities 1.6.4.2
  + SuperVanish 6.2.6
  + CustomCrafting 1.6.6.0
  + dtlTraders 6.4.1
  + EliteMobs 7.3.1-SNAPSHOT-3
  + SpecializedCrates 2.19.42
  + QuickShop 4.0.8.3-SNAPSHOT
  + Brewery 3.0
  + Slimefun DEV - 930 (git 0224f94e)
  + SlimefunOreChunks DEV - 13 (git 9f7a2be3)
  + ExtraHeads DEV - 21 (git a2c68d59)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + FluffyMachines DEV - 84 (git cf78f53a)
  + DyedBackpacks DEV - 15 (git 5f5e8b9e)
  + SensibleToolbox DEV - 40 (git f3e782d3)
  + ExtraGear DEV - 12 (git 4570ea2c)
  + SFCalc DEV - 24 (git 2574e3e0)
  + TranscEndence DEV - 34 (git eece87db)
  + GeneticChickengineering DEV - 13 (git 37cffcbb)
  + ChestTerminal DEV - 43 (git 3096bab5)
  + HeadLimiter DEV - 3 (git 58cfca94)
  + LiteXpansion DEV - 152 (git daa388b9)
  + InfinityExpansion DEV - 114 (git 9d5d3cec)
  - DynaTech DEV - 121 (git ef38d195)
  + FurnitureLib 2.4.3
  + DiceFurniture 3.4.6
  + ProtectionLib 1.1
  + BigDoors Alpha 0.1.8.29 (b957)
  + BigDoorsOpener 2.4.1b
  + StaffPlus 3.3.5.0
  + CoreProtect 19.5
  + UltimateTimber 2.2.4
  + PlayerWarps 6.7.0
  + ChatControl 5.9.1
  + CasinoPlugin 4.1.0
  + VoidSpawn 1.19.3
  + Multiverse-Core 4.2.2-b812
  + DiscordSRV 1.22.0
  + BentoBox 1.16.2
  + GriefPrevention 16.17.1-2b69191

Block Info:
  World: bskyblock_world
  X: -787
  Y: 123
  Z: -816
  Material: BLAST_FURNACE
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftBlastFurnace
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlastFurnace

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: GCE_EXCITATION_CHAMBER
  Inventory: true
  Data: {"energy-charge":"250","id":"GCE_EXCITATION_CHAMBER"}

Stacktrace:

java.lang.NoSuchMethodError: 'boolean space.kiichan.geneticchickengineering.machines.ExcitationChamber.isProcessing(org.bukkit.block.Block)'
	at space.kiichan.geneticchickengineering.machines.ExcitationChamber.tick(ExcitationChamber.java:100)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:339)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:188)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:175)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:145)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:114)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by mrcoffee1026** [comment]
dupe of #15

**Comment by PcampusNetwork** [comment]
yeaa i have same issue

**Comment by kubaking01** [comment]
me too

**Comment by kubaking01** [comment]
Error Generated: 2021-07-30-21-36

Java Environment:
  Operating System: Linux
  Java Version: 16.0.1

Server Software: Paper
  Build: git-Paper-783 (MC: 1.16.5)
  Minecraft v1.16.5-R0.1-SNAPSHOT

Slimefun Environment:
  Slimefun vDEV - 956 (git 0262830e)
  Caused by: GeneticChickengineering v1.2.0

Installed Addons (15)
  + EcoPower DEV - 4 (git 2a08d31d)
  + SlimefunLuckyBlocks DEV - 35 (git 3b6586d6)
  + SoulJars DEV - 22 (git aded79dd)
  + ExtraTools DEV - 28 (git 58488a2e)
  + SlimefunOreChunks DEV - 14 (git b08809bc)
  + SimpleMaterialGenerators DEV - 6 (git 2083e132)
  + ExtraGear DEV - 12 (git 4570ea2c)
  + ElectricSpawners DEV - 22 (git 4cb2c56b)
  + MobCapturer DEV - 15 (git a42c9e0c)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + PrivateStorage DEV - 17 (git 43d35d74)
  + GeneticChickengineering 1.2.0
  + ChestTerminal DEV - 43 (git 3096bab5)
  - LiteXpansion DEV - 154 (git 19479f8c)
  + InfinityExpansion DEV - 117 (git 1ca379e0)

Installed Plugins (26):
  + CoreProtect 19.5
  + CratesPlus 4.5.3
  + LuckPerms 5.3.47
  + SilkSpawners 7.1.0
  + ProtocolLib 4.6.0
  + HostifyMonitor 1.6
  + Brewery 3.1
  + SkinsRestorer 14.1.1
  + ImageMaps 1.0.6
  + Slimefun DEV - 956 (git 0262830e)
  + EcoPower DEV - 4 (git 2a08d31d)
  + SlimefunLuckyBlocks DEV - 35 (git 3b6586d6)
  + SoulJars DEV - 22 (git aded79dd)
  + ExtraTools DEV - 28 (git 58488a2e)
  + SlimefunOreChunks DEV - 14 (git b08809bc)
  + SimpleMaterialGenerators DEV - 6 (git 2083e132)
  + ExtraGear DEV - 12 (git 4570ea2c)
  + AuthMe 5.6.0-SNAPSHOT-b2469
  + ElectricSpawners DEV - 22 (git 4cb2c56b)
  + MobCapturer DEV - 15 (git a42c9e0c)
  + SlimyTreeTaps DEV - 19 (git 69930ef7)
  + PrivateStorage DEV - 17 (git 43d35d74)
  + GeneticChickengineering 1.2.0
  + ChestTerminal DEV - 43 (git 3096bab5)
  - LiteXpansion DEV - 154 (git 19479f8c)
  + InfinityExpansion DEV - 117 (git 1ca379e0)

Block Info:
  World: world
  X: -4266
  Y: 78
  Z: 65
  Material: BLAST_FURNACE
  Block Data: org.bukkit.craftbukkit.v1_16_R3.block.impl.CraftBlastFurnace
  State: org.bukkit.craftbukkit.v1_16_R3.block.CraftBlastFurnace

Ticker-Info:
  Type: Asynchronous

Slimefun Data:
  ID: GCE_EXCITATION_CHAMBER
  Inventory: true
  Data: {"energy-charge":"250","id":"GCE_EXCITATION_CHAMBER"}

Stacktrace:

java.lang.NoSuchMethodError: 'boolean space.kiichan.geneticchickengineering.machines.ExcitationChamber.isProcessing(org.bukkit.block.Block)'
	at space.kiichan.geneticchickengineering.machines.ExcitationChamber.tick(ExcitationChamber.java:100)
	at me.mrCookieSlime.Slimefun.Objects.SlimefunItem.abstractItems.AContainer$3.tick(AContainer.java:339)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickBlock(TickerTask.java:188)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickLocation(TickerTask.java:175)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.tickChunk(TickerTask.java:145)
	at io.github.thebusybiscuit.slimefun4.implementation.tasks.TickerTask.run(TickerTask.java:114)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftTask.run(CraftTask.java:100)
	at org.bukkit.craftbukkit.v1_16_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)

**Comment by kubaking01** [comment]
and private coop

**Comment by ybw0014** [comment]
https://github.com/kii-chan-reloaded/GeneticChickengineering/issues/21
